### ISSUE TITLE
Investigate Github API

### ISSUE THREAD

**Issue by darktasevski** [interventure-growingtogether/hackathon19-contrihub#1]
Should we use REST or GraphQL for fetching data about repositories.

**Comment by SasaJonic** [comment]
Search repos by searchword in name, topic and language:
curl -i "https://api.github.com/search/repositories?q=primer+in:name+language:python+topic:python&sort=stars&order=desc"

**Comment by SasaJonic** [comment]
Get repo by id:
curl -i "https://api.github.com/repositories/83222441"
